build:
    environment:
        timezone: Europe/Amsterdam
        php:
            ini:
                'memory_limit': "-1"
        mysql: false
        postgresql: false
        redis: false
        elasticsearch: false
        rabbitmq: false
        mongodb: false
        neo4j: false
        node: false
        memcached: false
    tests:
        stop_on_failure: true
    nodes:
        analysis:
            resources:
                cpus: 2
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: false
        php70:
            environment:
                php: "7.0"
            tests:
                after:
                    -
                        command: 'vendor/bin/phpunit --coverage-clover=clover.xml'
                        coverage:
                            file: 'clover.xml'
                            format: 'clover'
                        on_node: 1
                        idle_timeout: 600
        php72:
            environment:
                php: "7.2"
            tests:
                after:
                    -
                        command: 'vendor/bin/phpunit'
                        on_node: 1
                        idle_timeout: 600
filter:
    excluded_paths:
        - 'tests/*'
    dependency_paths:
        - 'vendor/*'
checks:
    php: true
tools:
    sensiolabs_security_checker: true
